version: '3'
services:
  web:
    build: ./web
    volumes:
    - '../:/var/www/html'
    environment:
      VIRTUAL_HOST: 'strategy.go-hd.net'
      VIRTURL_PORT: 80
      LETSENCRYPT_HOST: 'strategy.go-hd.net'
      LETSENCRYPT_EMAIL: 'y.kawamoto@go-hd.jp'
    restart: always
  composer:
    build: ./composer
    volumes:
    - '../:/data'
networks:
  default:
    external:
      name: ${NETWORK_NAME}
